id: P010663
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14794
  title: ཏུན་ཧོང་བོད་བཙན་པོའི་དུས་ཀྱི་རིག་གནས་དཔྱད་གླེང་ཚོགས་འདུའི་དཔྱད་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    ed356b610020430b9d38ed1f96f9a71a:
      image_group_id: I1KG14925
      title: ''
      volume_number: 1
      total_pages: 514
      base_file: v001.txt
