id: IE84F53F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T03:06:35+00:00'
last_modified: '2022-06-08T16:36:22.501368+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14794
  title: ཏུན་ཧོང་བོད་བཙན་པོའི་དུས་ཀྱི་རིག་གནས་དཔྱད་གླེང་ཚོགས་འདུའི་དཔྱད་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    5F82:
      image_group_id: I1KG14925
      title: ''
      total_pages: 514
      order: 1
      base_file: 5F82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
